### ISSUE TITLE
Flights

### ISSUE THREAD

**Issue by MetaEMK** [MetaEMK/FGK_PASMAS_frontend#23]
## Logic
- [x] It is not allowed to have more than 1 flight at the same time and plane
- [x] MTOW calculation
- [x] See comments

## Attributes
- [x] Type (Blocker, reserved, booked)
- [x] Plane - see MetaEMK/FGK_PASMAS_backend#21 
- [x] Fuel
- [x] Start time
- [x] Landing time
- [x] Passenger
- [x] MetaEMK/FGK_PASMAS_backend#25

**Comment by J-C-V** [comment]
logic implemented
