### ISSUE TITLE
flight overview

### ISSUE THREAD

**Issue by MetaEMK** [MetaEMK/FGK_PASMAS_frontend#27]
if possible make to overviews:
1. all flights
2. only flights with time.Now() - 3 min <= flight.DepartureTime

need parameters:
- **plane.Registration**
- (opt) plane.AircraftType
- flight.FlightNo
- **flight.DepartureTime**
- flight.ArrivalTime
- **flight.Description**
- Pilot.FirstName + Pilot.LastName
- all **passenger.PassengerNo (currently missing - replace it with ID)**

**Comment by J-C-V** [comment]
implemented for backend v0.2.0
changes for backend v0.4.0 will be implemented in frontend v0.3.0

**Comment by J-C-V** [comment]
moved to #36
