### ISSUE TITLE
BUG: all Table filter dont work with edit or view (open dialog) buttons

### ISSUE THREAD

**Issue by MetaEMK** [MetaEMK/FGK_PASMAS_frontend#50]
## Version
v0.5

## Page
Flugzeuge or Flüge
Works for all primeview tables with any button per row

## Description
The wrong edit dialogue of the aircraft opens when you filter for "registration"

## Steps to reproduce
1. Filter registration to any plane which is not the first one
2. Select the edit button of "new" first plane
3. The edit dialog of the "old" first plane opens

## Expected behaviour:
The edit dialog of the selected plane opens

**Comment by MetaEMK** [comment]
Hotfix disable filtering

**Comment by J-C-V** [comment]
fixed
